ADuCM4x50 Device Drivers API Reference Manual: System Interfaces
System Interfaces
Macros
#define ADI_SRAM_BANK_0 (1u << 0)
#define ADI_SRAM_BANK_1 (1u << 1)
#define ADI_SRAM_BANK_2 (1u << 2)
#define ADI_SRAM_BANK_3 (1u << 3)
#define ADI_SRAM_BANK_4 (1u << 4)
#define ADI_SRAM_BANK_5 (1u << 5)
#define ADI_SRAM_BANK_6 (1u << 6)
#define ADI_SRAM_BANK_7 (1u << 7)
Typedefs
typedef uint32_t ADI_SRAM_BANK
Enumerations
enum ADI_SYS_RESULT {
ADI_SYS_SUCCESS = 0,
ADI_SYS_FAILURE
}
Functions
void SystemInit (void)
Sets up the microcontroller system. Initializes the System and updates the relocate vector table.
void SystemCoreClockUpdate (void)
Update the clock.
void adi_system_EnableCache (bool bEnable)
Enables or disables the cache.
ADI_SYS_RESULT adi_system_EnableRetention (ADI_SRAM_BANK eBank, bool bEnable)
This enables/disable SRAM retention during the hibernation.
void adi_system_EnableISRAM (bool bEnable)
This enables or disables instruction SRAM.
Variables
uint32_t SystemCoreClock = 0u
Detailed Description
System global interfaces and CMSIS required variables
Macro Definition Documentation
#define ADI_SRAM_BANK_0 (1u << 0)
SRAM_BANK_0
Definition at line 125 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention().
#define ADI_SRAM_BANK_1 (1u << 1)
SRAM_BANK_1
Definition at line 127 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention(), and SystemInit().
#define ADI_SRAM_BANK_2 (1u << 2)
SRAM_BANK_2
Definition at line 129 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention().
#define ADI_SRAM_BANK_3 (1u << 3)
SRAM_BANK_3
Definition at line 131 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention(), and SystemInit().
#define ADI_SRAM_BANK_4 (1u << 4)
SRAM_BANK_4
Definition at line 133 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention(), and SystemInit().
#define ADI_SRAM_BANK_5 (1u << 5)
SRAM_BANK_5
Definition at line 135 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention(), and SystemInit().
#define ADI_SRAM_BANK_6 (1u << 6)
SRAM_BANK_6
Definition at line 137 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention(), and SystemInit().
#define ADI_SRAM_BANK_7 (1u << 7)
SRAM_BANK_7
Definition at line 139 of file system_ADuCM4050.h.
Referenced by adi_system_EnableRetention(), and SystemInit().
Typedef Documentation
typedef uint32_t ADI_SRAM_BANK
SRAM banks
Definition at line 122 of file system_ADuCM4050.h.
Enumeration Type Documentation
enum ADI_SYS_RESULT
System API function return codes
Enumerator
ADI_SYS_SUCCESS
No error detected.
ADI_SYS_FAILURE
The API call failed.
Definition at line 71 of file system_ADuCM4050.h.
Function Documentation
void SystemInit (void)
Sets up the microcontroller system. Initializes the System and updates the relocate vector table.
Returns
none
Note
This function is called by the start-up code and does not need to be called directly by applications
Definition at line 219 of file system_ADuCM4050.c.
void SystemCoreClockUpdate (void)
Update the clock.
Updates the variable SystemCoreClock and must be called whenever the core clock is changed during program execution.
Returns
none
Definition at line 145 of file system_ADuCM4050.c.
Referenced by adi_pwr_GetClockFrequency(), adi_pwr_Init(), adi_pwr_SetClockDivider(), and adi_pwr_UpdateCoreClock().
void adi_system_EnableCache (bool bEnable)
Enables or disables the cache.
Parameters
bEnable Specify whether to enable/disable cache.
true : Enable cache.
false: Disable cache.
Returns
none
Definition at line 290 of file system_ADuCM4050.c.
Referenced by SystemInit().
ADI_SYS_RESULT adi_system_EnableRetention (ADI_SRAM_BANK eBank, bool bEnable)
This enables/disable SRAM retention during the hibernation.
Parameters
eBank Specify which SRAM banks. Multiple banks can be set / using a logical OR of the banks.
bEnable Enable/disable the retention for specified SRAM bank.
true : Enable retention during hibernation.
false: Disable retention during hibernation.
Returns
ADI_SYS_SUCCESS Configured successfully.
ADI_SYS_FAILURE Invalid bank, or banks, specified. Any incorrect or invalid bank options will result in failure and no changes will have been applied.
Note
The appropriate linker file needs to support the configuration. BANK 0 is always retained. BANKS 1 can be retained individually. BANK 2 is never retained. BANKS 3 and 4 can only be mutually retained. BANKS 5 can be retained individually. BANKS 6 and 7 can only be mutually retained.
Definition at line 344 of file system_ADuCM4050.c.
Referenced by SystemInit().
void adi_system_EnableISRAM (bool bEnable)
This enables or disables instruction SRAM.
Parameters
bEnable Enable/disable the instruction SRAM.
true : Enable instruction SRAM.
false : Disable instruction SRAM.
Returns
none
Note
The appropriate linker file needs to support the configuration.
Definition at line 312 of file system_ADuCM4050.c.
Referenced by SystemInit().
Variable Documentation
uint32_t SystemCoreClock = 0u
System Clock Frequency (Core Clock)
Definition at line 131 of file system_ADuCM4050.c.